version: 2
jobs:
  one:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_directory
      - run: echo "Trying out workspaces" > my_directory/echo-output
      - persist_to_workspace:
          root: my_directory
          paths:
            - echo-output

  two:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
          at: my_directory
      - run: |
          if [[ $(cat my_directory/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
