version: 2
jobs:
  one:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: ls
      - run: echo "A first hello"
      - run: sleep 25

  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "A second hello"
      - run: sleep 15

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
